### ISSUE TITLE
Isolate SD card issues

### ISSUE THREAD

**Issue by UCLARocketProject** [UCLARocketProject/2014-2015#13]
1. When do we get SD card corruption? Pulling power? Yanking card out while it's writing? Can we get rid of the open/close file paradigm?
2. Can we speed up writes of lines to the SD card?

**Comment by UCLARocketProject** [comment]
We cannot get rid of the `open()`/`close()` paradigm. `file.close()` is when we actually physically write to the file on the SD card [[1](http://www.arduino.cc/en/Reference/FileClose)].

**Comment by off-by-one** [comment]
We can use file.flush() on writes - that writes any data in the buffer to the SD card. That way, it's not necessary to open and close the file on every single loop iteration.

**Comment by UCLARocketProject** [comment]
Perfect! For later reference, `file.flush()` is documented [here](http://www.arduino.cc/en/Reference/FileFlush).

**Comment by UCLARocketProject** [comment]
Reading and writing in batches (https://github.com/UCLARocketProject/2014-2015/commit/c59c95c6d84de6bf871277669281ead771dc1dbe) effectively addresses both of these issues.
