### ISSUE TITLE
Data rates not in scope

### ISSUE THREAD

**Issue by UCLARocketProject** [UCLARocketProject/2014-2015#16]
Our custom LSM303 library is interfering with the data rate values from being seen: 

```
client-compLaunch.ino:65:29: error: 'LSM303_ACCEL_DATA_RATE_400HZ' was not declared in this scope
client-compLaunch.ino:66:29: error: 'LSM303_MAG_DATA_RATE_220HZ' was not declared in this scope
```

For reference, here are lines [64-66](https://github.com/UCLARocketProject/2014-2015/blob/master/Radio%20System/compLaunch/client-compLaunch/client-compLaunch.ino#L65):

``` c
    // Initialize the sensors
    accel.setDataRate((byte)LSM303_ACCEL_DATA_RATE_400HZ);
    accel.setDataRate((byte)LSM303_MAG_DATA_RATE_220HZ);
```

**Comment by off-by-one** [comment]
I can't reproduce this error. Our custom libraries are the ones that defined these values, and the setDataRate function. Did you install it?

**Comment by KyCodeHuynh** [comment]
I did, so I don't know why I get this error. I'll try again later. 

## 

Ky-Cuong Huynh

**Comment by atomar94** [comment]
When you include the library using the arduino ide make sure you are
including the custom one. The ide might be storing the library under the
same name as another.

Alexander Omar
B.S. Computer Engineer (Spring 2017)
University of California Los Angeles
(530)448-3778

**Comment by UCLARocketProject** [comment]
Fixed by copying Alex's libraries atop Ky-Cuong.
