### ISSUE TITLE
Roll and X acceleration are reading the same thing 

### ISSUE THREAD

**Issue by atomar94** [UCLARocketProject/2014-2015#17]
X acceleration is reading x acceleration but orientation.roll is also reading the acceleration in the x axis

**Comment by UCLARocketProject** [comment]
Redundant with issue https://github.com/UCLARocketProject/2014-2015/issues/18

**Comment by atomar94** [comment]
Ky Cuong fixed this. Good Job Ky Cuong. Good job.

**Comment by haydenjohnson** [comment]
Good job Ky Ching!
