### ISSUE TITLE
Temperature data not separated by newlines

### ISSUE THREAD

**Issue by UCLARocketProject** [UCLARocketProject/2014-2015#2]
Temperature data is currently not separated by newlines. For example, in the file `today.txt` on the (big) SD card after the tempToSDCard sketch writes to it: 

```
20.3820.3820.3820.3820.3820.3820.3820.3820.3820.38
```

This should be: 

```
20.38
20.38
20.38
20.38
20.38
20.38
20.38
20.38
20.38
20.38
20.38
```

**Comment by KyCodeHuynh** [comment]
Latest format for temperature data avoids this issue altogether.
