### ISSUE TITLE
Choose radio control library

### ISSUE THREAD

**Issue by KyCodeHuynh** [UCLARocketProject/2014-2015#5]
Which radio library shall we use? RadioHead looks promising. Multiple specifications and implementations are waiting on this choice to be made.

**Comment by atomar94** [comment]
Kai just ordered the [nRF24L01](http://www.amazon.com/nRF24L01-Wireless-Transceiver-Arduino-Compatible/dp/B00E594ZX0/ref=sr_1_1?ie=UTF8&qid=1425210502&sr=8-1&keywords=nrf24l01%2B) so whichever one supports that radio and seems easiest would be my bet.

**Comment by KyCodeHuynh** [comment]
From today's meeting: we're going to use [RadioHead](http://www.airspayce.com/mikem/arduino/RadioHead/index.html)
