### ISSUE TITLE
Analysis of Large Data Sets

### ISSUE THREAD

**Issue by KyCodeHuynh** [UCLARocketProject/2014-2015#6]
This should be doable with [gnuplot](http://www.gnuplot.info) and raw statistics can be computed by hand on disk if need be. Data would be read/written via I/O system calls like read() and write(). 

[Graphviz](http://graphviz.org) may also be of use, as well as LaTeX.

**Comment by atomar94** [comment]
MatLab has the ability to plot massive (1 billion point) datasets. GNU plot seems easier to use though because we don't need to do much work to set it up. Let's go with GNU plot for now and if they want extra analysis they have enough matlab programmers to build a new plotting system.
