### ISSUE TITLE
Dynamic filenames

### ISSUE THREAD

**Issue by UCLARocketProject** [UCLARocketProject/2014-2015#8]
We need dynamic filenames for writing to the SD card. 

In [client-compLaunch.ino](https://github.com/UCLARocketProject/2014-2015/blob/master/Radio%20System/compLaunch/client-compLaunch/client-compLaunch.ino), 
we currently have a hard-coded filename: 

``` arduino
const char* FILENAME = "run2-26.txt";
```

**Comment by UCLARocketProject** [comment]
Using the [Time](http://www.pjrc.com/teensy/td_libs_Time.html) library should be helpful for this.

**Comment by atomar94** [comment]
Added dynamic filenames to the sdWrite.ino file
